{{- range $i, $org := .Values.PeerOrgs }}
{{- $vars:= dict "firstKey" true }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-ca--{{ $org.Name | lower }}-tls
  labels:
    orgName: {{ $org.Name }}
data:
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/ca/ca.%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}

  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/peerOrganizations/%s/ca/*_sk" $org.Domain ) }}
  {{- if not $vars.firstKey }}
    {{ fail (printf "Multiple private keys in folder: crypto-config/peerOrganizations/%s/ca/" $org.Domain ) }}
  {{- end }}
  private_key: |-
      {{ $.Files.Get $path | b64enc }}
      {{- $_ := set $vars "firstKey" false }}
  {{- end }}

---
{{- end }} {{- /* Orgs */ -}}
