# This is a workaround to the docker pull rate limit issue. 
# The image fabric_images.ccenv is pulled at runtime inside another container and if we reach the pull rate limit, pulling this specific image will prevent executing `peer lifecycle chaincode install .. ` command. 
# Using DaemonSet, we can pre-pull once the image in all the nodes. 

{{- if not .Values.use_docker_credentials }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
  annotations:
    source: "https://gist.github.com/itaysk/7bc3e56d69c4d72a549286d98fd557dd"
spec:
  selector:
    matchLabels:
      name: prepull 
  template:
    metadata:
      labels:
        name: prepull 
    spec:
      imagePullSecrets:
        - name: regcred

      initContainers:
      - name: prepull 
        image: docker
        command: ["docker", "pull", {{ .Values.fabric_images.ccenv }} ]
        volumeMounts:
        - name: docker
          mountPath: /var/run
      volumes:
      - name: docker
        hostPath:
          path: /var/run
      containers:
      - name: pause
        image: gcr.io/google_containers/pause

{{- end }}