{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}-tls
  labels:
    orgName: {{ $org.Name }}
    peerName: {{ $peer }}
data:
  ca.crt: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/tls/ca.crt" $org.Domain $peer $org.Domain ) | b64enc }}
  server.crt: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/tls/server.crt" $org.Domain $peer $org.Domain ) | b64enc }}
  server.key: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/tls/server.key" $org.Domain $peer $org.Domain ) | b64enc }}

---
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}
