# Ansible Playbook to create Openstack Instances for Kubernetes cluster setup
# Note: Call with -i inventory/infra/hosts.ini
# ---
# - hosts: controle_node
#   become: yes
#   become_user: root
#   become_method: sudo
#   tasks:
#     - name: Update repositories cache and install "python3-pip" package
#       apt:
#         name: python3-pip
#         update_cache: yes
---
- hosts: kube-master
  gather_facts: True
  tasks:
    - name: "loop through list"
      debug:
        msg: "An item: {{item}}"
      with_items:
        - var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
