# Ansible Playbook to setup kubectl
# Note: Call with -i hosts
---
- hosts: kube-master
  gather_facts: True
  tasks:
    - name: Create cluster setup inventory
      template: src=cluster.hosts.ini.j2 dest=hosts.ini mode=0644
      delegate_to: localhost

    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Configure kubectl after setting up k8s cluster
      command: scripts/kubectl_configure.sh {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      delegate_to: localhost
      register: ps

    - debug: var=ps.stdout_lines
    
    - name: Install Argo
      ansible.builtin.shell: |
        kubectl create namespace argo
        kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v3.0.0-rc5/manifests/install.yaml
        kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
      delegate_to: localhost
      register: ps
