# Ansible Playbook to setup kubectl
# Note: Call with -i hosts
---
- hosts: kube-master
  gather_facts: True
  tasks:
    - name: Create cluster setup inventory
      template: src=cluster.hosts.ini.j2 dest=hosts.ini mode=0644
      delegate_to: localhost

    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

    - name: Configure kubectl after setting up k8s cluster
      command: scripts/configure_kubectl.sh {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      delegate_to: localhost
      register: ps

    - debug: var=ps.stdout_lines
# TODO ADD ARGO CLI AND CONTROLLER INSTALLATIONS. STEPS CAN BE FOUND IN NOTE
# - name: Install Argo
#   command: scripts/configure_kubectl.sh {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
#   delegate_to: localhost
#   register: ps
