# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
{{- $root := . -}}
PeerOrgs:
  - Name: OrdOrg1
    Domain: {{ $root.Values.fabric_orderer_domain }}
    EnableNodeOUs: true
    Specs:
    {{- range untilStep 1 (int .Values.fabric_num_orderer) 1 }}
      - Hostname: orderer{{.}}
    {{- end }}

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
{{- range untilStep 1 (int .Values.fabric_num_orgs) 1 }}
  - Name: Org{{.}}
    Domain: org{{.}}
    EnableNodeOUs: true
    Template:
      Count:  {{ $root.Values.fabric_peers_per_org }}
{{- end }}