# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdOrg1
    Domain: org1
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1

  - Name: OrdOrg2
    Domain: org2
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
{{- range untilStep 1 (int .Values.fabric_num_orgs) 1 }}
  - Name: Org{{.}}
    Domain: org{{.}}
    EnableNodeOUs: true
    Template:
      Count: (int .Values.fabric_peers_per_org)
{{ end }}
  - Name: Org1
    Domain: org1
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1