test:
  workers:
    number: 16
  rounds:
    - label: Create a car .
      txNumber: 20000
      rateControl:
        type: fixed-rate
        opts:
          tps: 1100
          # transactionLoad: 2000
      workload:
        module: /caliper-workload/createCar.js
