test:
  workers:
    number: 5
  rounds:
    - label: Create a car.
      txNumber: 1000
      rateControl:
          type: linear-rate
          opts:
            startingTps: 100
            finishingTps: 500
      workload:
        module: /caliper-workload/createCar.js

    - label: Change car owner.
      txNumber: 1000
      rateControl:
          type: linear-rate
          opts:
            startingTps: 100
            finishingTps: 500
      workload:
        module: /caliper-workload/changeCarOwner.js
        arguments:
          assets: 500
    # - label: Query all cars.
    #   txNumber: 1000
    #   rateControl:
    #       type: fixed-load
    #       opts:
    #         transactionLoad: 5
    #   workload:
    #     module: /caliper-workload/queryAllCars.js
    #     arguments:
    #       assets: 20
    #       startKey: '1'
    #       endKey: '50'
    - label: Query a car.
      txNumber: 2000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 3000
          transactionLoad: 10
      workload:
        module: /caliper-workload/queryCar.js
        arguments:
          assets: 1000
