test:
  workers:
    number: 10
  rounds:
    - label: Change car owner.
      txDuration: 10
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 100
          transactionLoad: 10
      workload:
        module: /caliper-workload/changeCarOwner.js
        arguments:
          assets: 10
    # - label: Query all cars.
    #   txDuration: 20
    #   rateControl:
    #     type: fixed-feedback-rate
    #     opts:
    #       tps: 500
    #       transactionLoad: 10
    #   workload:
    #     module: /caliper-workload/queryAllCars.js
    #     arguments:
    #       assets: 10
    #       startKey: '1'
    #       endKey: '50'
    - label: Query a car.
      txDuration: 2
      rateControl:
        type: fixed-rate
        opts:
          tps: 3000
      workload:
        module: /caliper-workload/queryCar.js
        arguments:
          assets: 10
    - label: Create a car.
      txDuration: 10
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 1000
          transactionLoad: 10
      workload:
        module: /caliper-workload/createCar.js
