test:
  workers:
    number: 16
  rounds:
    - label: Create a car .
      txDuration: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 800
      workload:
        module: /caliper-workload/createCar.js
