test:
  workers:
    number: 5
  rounds:
    - label: Create a car.
      txNumber: 200
      rateControl:
          type: maximum-rate
          opts:
            tps: 1000
            step: 10
            sampleInterval: 20
            includeFailed: false
      workload:
        module: /caliper-workload/createCar.js

    - label: Change car owner.
      txNumber: 200
      rateControl:
          type: maximum-rate
          opts:
            tps: 1000
            step: 10
            sampleInterval: 20
            includeFailed: false
      workload:
        module: /caliper-workload/changeCarOwner.js
        arguments:
          assets: 1000
    # - label: Query all cars.
    #   txNumber: 1000
    #   rateControl:
    #       type: fixed-load
    #       opts:
    #         transactionLoad: 5
    #   workload:
    #     module: /caliper-workload/queryAllCars.js
    #     arguments:
    #       assets: 20
    #       startKey: '1'
    #       endKey: '50'
    - label: Query a car.
      txNumber: 5000
      rateControl:
          type: maximum-rate
          opts:
            tps: 3000
            step: 200
            sampleInterval: 20
            includeFailed: false
      workload:
        module: /caliper-workload/queryCar.js
        arguments:
          assets: 1000
