test:
  workers:
    number: 10
  rounds:
    - label: Change car owner.
      txNumber: 100
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 100
          transactionLoad: 20
      workload:
        module: /caliper-workload/changeCarOwner.js
        arguments:
          assets: 10
    - label: Query all cars.
      txNumber: 1000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 2000
          transactionLoad: 20
      workload:
        module: /caliper-workload/queryAllCars.js
        arguments:
          assets: 10
          startKey: '1'
          endKey: '50'
    - label: Query a car.
      txNumber: 1000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 2000
          transactionLoad: 20
      workload:
        module: /caliper-workload/queryCar.js
        arguments:
          assets: 10
    - label: Create a car.
      txDuration: 30
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 1000
          transactionLoad: 20
      workload:
        module: /caliper-workload/createCar.js
