test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 5
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 2000
      rateControl: 
        type: fixed-rate
        opts:
          tps: 2000
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
    - label: createAsset
      description: Create asset benchmark
      txNumber: 1000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 500
          transactionLoad: 10
      workload:
        module: /caliper-workload/createAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
    - label: transferAsset
      description: Transfer asset benchmark
      txNumber: 1000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 500
          transactionLoad: 10
      workload:
        module: /caliper-workload/transferAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic

monitors:
    transaction:
    - module: logging
      options:
        loggerModuleName: txinfo
        messageLevel: info