test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txDuration: 10
      rateControl: 
        type: fixed-rate
        opts:
          tps: 3000
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
    - label: createAsset
      description: Create asset benchmark
      txDuration: 10
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 1000
          transactionLoad: 10
      workload:
        module: /caliper-workload/createAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic

monitors:
    transaction:
    - module: logging
      options:
        loggerModuleName: txinfo
        messageLevel: info