test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 2
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txDuration: 2
        rateControl:
          type: fixed-rate
          opts:
            tps: 3000
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
monitors:
    transaction:
    - module: logging
      options:
        loggerModuleName: txinfo
        messageLevel: info