# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererOrg1
    Domain: ordererOrg1
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
  - Name: OrdererOrg2
    Domain: ordererOrg2
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: Org2
    Domain: org2
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org3
    Domain: org3
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1