# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
  - Name: Org2
    Domain: org2
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org3
    Domain: aptalorg3
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: Org4
    Domain: org4
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org5
    Domain: org5
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1