# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdOrg1
    Domain: org1
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      # - Hostname: orderer1
  # - Name: OrdOrg2
  #   Domain: org2
  #   EnableNodeOUs: true
  #   Specs:
  #     - Hostname: orderer0

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 1

  - Name: Org2
    Domain: org2
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 1

  # - Name: Org3
  #   Domain: org3
  #   EnableNodeOUs: true
  #   Template:
  #     Count: 2
  #   Users:
  #     Count: 1
