test:
  name: create-asset-size-ramp
  description: >-
    This is a duration based benchmark targeting a Hyperledger Fabric network
    using the `fixed-asset` chaincode that is interacted with via a Fabric-SDK-Node Gateway. 
  workers:
    number: 8
  rounds:
    - label: create-asset-100
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `fixed-asset` Smart Contract method named `createAsset`, which inserts
        an asset of size 100 bytes into the World State database.
      chaincodeID: fixed-asset
      txDuration: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 2200
      workload:
        module: /caliper-workload/create-asset.js
        arguments:
          chaincodeID: fixed-asset
  