# Default values for hlf-kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
retryCount: 4

logLevel: grpc=debug:info

flow:
  channel:
    # should we run top level channel flows in parallel?
    parallel: false
    # fill in this array with channel names to limit the channel flow only to these ones
    include: []
  join:
    # run channel join flows in parallel?
    parallel: true
  update:
    # run channel update flows in parallel?
    parallel: true
