test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 5000
      rateControl:
        type: fixed-load
        opts:
          # tps: 2000
          startingTps: 1000
          transactionLoad: 5
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
