test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 20000
      rateControl:
        type: fixed-rate
        opts:
          tps: 2000
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
