test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 2500  
      rateControl:
        type: fixed-rate
        opts:
          tps: 2500
          # startingTps: 3000
          # transactionLoad: 10
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
