test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 5000
      rateControl:
        type: fixed-feedback-rate
        opts:
          tps: 1000
          # startingTps: 3000
          transactionLoad: 2500
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
