test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 10
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 5000
      rateControl:
        type: fixed-backlog
        opts:
          # tps: 2000
          unfinished_per_client: 5
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20
          contractId: asset-transfer-basic
