test:
  name: basic-contract-benchmark
  description: test benchmark
  workers:
    number: 1
  rounds:
    - label: readAsset
      description: Read asset benchmark
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
          # startingTps: 3000
          # transactionLoad: 10
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 5
          contractId: asset-transfer-basic
