# test:
#   name: marble-benchmark
#   description: test benchmark
#   workers:
#     number: 1
#   rounds:
#     - label: initMarble
#       description: init marbles benchmark
#       txNumber: 100
#       rateControl:
#         type: fixed-load
#         opts:
#           tps: 25
#       workload:
#         module: workload/init.js
# monitor:
#   type:
#     - none

# observer:
#   type: local
#   interval: 1

test:
  name: basic-contract-benchmark
  description: test benchmark
  # workers:
  #   # type: local
  #   number: 1
  rounds:
    - label: readAsset
      description: Read asset benchmark
      txNumber: 20000
      rateControl:
        type: fixed-load
        opts:
          tps: 3000
      workload:
        module: /caliper-workload/readAsset.js
        arguments:
          assets: 20000
          contractId: asset-transfer-basic
