{{- range $i, $org := .Values.OrdererOrgs }}
{{- range $i, $host := $org.Specs }}
{{- $commonName := printf "%s.%s" $host.Hostname $org.Domain }}
{{- $vars:= dict "firstKey" true }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}-msp
  labels:
    orgName: {{ $org.Name }}
    commonName: {{ $commonName }}
data:
  config.yaml: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/config.yaml" $org.Domain $commonName ) | b64enc }}
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/signcerts/%s-cert.pem" $org.Domain $commonName $commonName ) | b64enc }}
  cacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/cacerts/ca.%s-cert.pem" $org.Domain $commonName $org.Domain) | b64enc }}
  admincert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/admincerts/Admin@%s-cert.pem" $org.Domain $commonName $org.Domain ) | b64enc }}

  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/ordererOrganizations/%s/orderers/%s/msp/keystore/*" $org.Domain $commonName ) }}
  {{- if not $vars.firstKey }}
    {{ fail (printf "Multiple private keys in folder: crypto-config/ordererOrganizations/%s/orderers/%s/msp/keystore/" $org.Domain $commonName ) }}
  {{- end }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
      {{- $_ := set $vars "firstKey" false }}
  {{- end }}
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* Orgs */ -}}
