{{- range $i, $org := .Values.OrdererOrgs }}
{{- range $i, $host := $org.Specs }}

apiVersion: v1
kind: Service
metadata:
  name: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
  labels:
    name: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
    component: hlf-orderer
    fqdn: {{ $host.Hostname }}.{{ $org.Domain }}
    addToHostAliases: "true"
spec:
  type: ClusterIP
  selector:
    app: hlf-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  {{- if $.Values.orderer.cluster.enabled }}
  - protocol: TCP
    port: {{ $.Values.orderer.cluster.port }}
    name: grpc-cluster
  {{- end }}  
  # to verify 
  {{- if $.Values.orderer.operations.enabled }}  
  - protocol: TCP
    port: {{ $.Values.orderer.operations.servicePort }}
    name: operations  
  {{- end }}  
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* OrdererOrgs */ -}}
