{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-peer--{{ $org.Name | lower }}--msp
  labels:
    orgName: {{ $org.Name }}
data:
  config.yaml: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/msp/config.yaml" $org.Domain ) | b64enc }}
  admincert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/msp/admincerts/Admin@%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}
  cacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/msp/cacerts/ca.%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}
  tlscacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/msp/tlscacerts/tlsca.%s-cert.pem" $org.Domain $org.Domain ) | b64enc }}
---
{{- end }} {{- /* PeerOrgs */ -}}
