apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caliper
  name: caliper
spec:
  selector:
    matchLabels:
      app: caliper
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: caliper
    spec:
      containers:
        - env:
            - name: CALIPER_BIND_SUT
              value: fabric:2.2
            - name: CALIPER_BENCHCONFIG
              value: /caliper-benchmark/myAssetBenchmark.yaml
            - name: CALIPER_NETWORKCONFIG
              value: /caliper-network/networkConfig.yaml
            - name: CALIPER_FABRIC_GATEWAY_ENABLED
              value: "true"
            - name: CALIPER_FLOW_ONLY_TEST
              value: "true"
          image: hyperledger/caliper:0.4.2
          name: caliper
          # command:
          #   - sleep
          # args:
          #   - "1000"
          # command:
          #   - caliper
          # args:
          #   - launch
          #   - manager
          tty: true
          volumeMounts:
            # - mountPath: /hyperledger/caliper/workspace
            #   name: caliper-workspace
            # - mountPath: /hyperledger/caliper/fabric
            #   name: fabric-workspace
            - mountPath: /etc/hyperledger/fabric/msp/
              name: peer-msp
            - mountPath: /etc/hyperledger/fabric/admin-msp/
              name: peer-admin-msp
            - mountPath: caliper-benchmark
              name: caliper-benchmark
            - mountPath: caliper-network
              name: caliper-network
            - mountPath: /hyperledger/caliper/workspace/
              name: caliper-config

          workingDir: /hyperledger/caliper/workspace
      restartPolicy: Never
      volumes:
        - name: caliper-workspace
          emptyDir: {}
        - name: caliper-benchmark
          configMap:
            name: benchmarks
        - name: caliper-network
          configMap:
            name: network
        - name: caliper-config
          configMap:
            name: caliper-config

        #   hostPath:
        #     path: /home/ubuntu/hyperledgerlab2/benchmarking
        #     type: DirectoryOrCreate
        # - name: fabric-workspace
        #   hostPath:
        #     path: /home/ubuntu/hyperledgerlab2/hyperledgerFabric
        #     type: DirectoryOrCreate
        - name: peer-msp
          secret:
            secretName: hlf-peer--org1--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp
          secret:
            secretName: hlf-peer--org1--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem
