apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliper-workspace-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: caliper-workspace-pv
  # hostPath:
  #   path: "/home/ubuntu/hyperledgerlab2/benchmarking"
  local:
    path: /home/ubuntu/hyperledgerlab2/benchmarking
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hlf-k8s-node-nf-2
