apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliper-workspace-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/hyperledgerlab2/benchmarking"
