apiVersion: v1
kind: PersistentVolume
metadata:
  name: caliper-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: caliper-pv
  local:
    path: /home/ubuntu/hyperledgerlab2/benchmarking
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hlf-k8s-node-nf-1
