apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: caliper
  name: caliper
spec:
  # selector:
  #   matchLabels:
  #     app: caliper //try to include selector
  # replicas: 4
  # strategy:
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: caliper
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Never
      containers:
        - name: caliper
          image: hyperledger/caliper:0.4.2
          # # command: ["/bin/sh"]
          # # args:
          # #   [
          # #     "-c",
          # #     "npm install -g npm && npm update -g && caliper launch manager",
          # #   ]
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["/bin/sh", "-c", "echo First container finished"]

          command:
            - caliper
          args:
            - launch
            - manager
          tty: true
          env:
            - name: CALIPER_BIND_SUT
              value: fabric:2.1
            - name: CALIPER_BENCHCONFIG
              value: /caliper-benchmark/myAssetBenchmark.yaml
            - name: CALIPER_NETWORKCONFIG
              value: /caliper-network/networkConfig.yaml
            - name: CALIPER_FABRIC_GATEWAY_ENABLED
              value: "true"
            - name: CALIPER_FABRIC_GATEWAY_LOCALHOST
              value: "false"
            - name: CALIPER_FLOW_ONLY_TEST
              value: "true"
            - name: CALIPER_WORKSPACE
              value: /hyperledger/caliper/workspace
            - name: CALIPER_BIND_ARGS
              value: "-g node-gyp"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric/peer-msp/
              name: peer-msp
            - mountPath: /etc/hyperledger/fabric/msp/
              name: peer-admin-msp
            - mountPath: /caliper-benchmark
              name: caliper-benchmark
            - mountPath: /caliper-network
              name: caliper-network
            - mountPath: /caliper-workload
              name: caliper-workload
            - mountPath: /caliper-chaincode
              name: caliper-chaincode
            - name: caliper-workspace
              mountPath: /hyperledger/caliper/workspace/
            # - name: caliper-config
            #   mountPath: /hyperledger/caliper/workspace/

      volumes:
        - name: caliper-workspace
          persistentVolumeClaim:
            claimName: caliper-workspace-pvc
        - name: caliper-benchmark
          configMap:
            name: benchmarks
        - name: caliper-network
          configMap:
            name: network
        - name: caliper-workload
          configMap:
            name: workload
        - name: caliper-config
          configMap:
            name: caliper-config
        - name: caliper-chaincode
          configMap:
            name: hlf-chaincode--asset-transfer-basic

        - name: peer-msp
          secret:
            secretName: hlf-peer--org1--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp
          secret:
            secretName: hlf-peer--org1--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem
