caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
      - id: fabcar

organizations:
  - mspid: org1MSP
    identities:
      certificates:
        - name: "Admin"
          admin: true
          clientPrivateKey:
            path: "/etc/hyperledger/fabric/admin-msp/keystore/priv_sk"
          clientSignedCert:
            path: "/etc/hyperledger/fabric/admin-msp/signcerts/cert.pem"
        - name: "User1"
          clientPrivateKey:
            path: "/etc/hyperledger/fabric/msp/keystore/priv_sk"
          clientSignedCert:
            path: "/etc/hyperledger/fabric/msp/signcerts/cert.pem"
    connectionProfile:
      path: "networks/profile-org1.yaml"
      discover: true
