name: Calier test
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.2.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /etc/hyperledger/fabric/msp/keystore/key.pem
      clientSignedCert:
        path: /etc/hyperledger/fabric/msp/signcerts/cert.pem
  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: /etc/hyperledger/fabric/msp/keystore/key.pem
      clientSignedCert:
        path: /etc/hyperledger/fabric/msp/signcerts/cert.pem

# organizations:
#   - mspid: org1MSP
#     identities:
#       certificates:
#         - name: "Admin"
#           admin: true
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/admin-msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/admin-msp/signcerts/cert.pem"
#         - name: "User1"
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/msp/signcerts/cert.pem"
#     connectionProfile:
#       path: "networks/profile-org1.yaml"

#       discover: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1
    certificateAuthorities:
      - ca-Org1
    adminPrivateKey:
      path: /etc/hyperledger/fabric/msp/keystore/key.pem
    signedCert:
      path: /etc/hyperledger/fabric/msp/signcerts/cert.pem
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2
    certificateAuthorities:
      - ca-Org2
    adminPrivateKey:
      path: /etc/hyperledger/fabric/msp/keystore/key.pem
    signedCert:
      path: /etc/hyperledger/fabric/msp/signcerts/cert.pem

certificateAuthorities:
  ca-Org1:
    url: https://hlf-ca--org1.default.svc.cluster.local:7054
    httpOptions:
      verify: false
    caName: ca-Org1
    tlsCACerts:
      path: /hlf_config/orderer-tlsca/tlscacert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
  ca-Org2:
    url: https://hlf-ca--org2.default.svc.cluster.local:7054
    httpOptions:
      verify: false
    caName: ca-Org2
    tlsCACerts:
      path: /hlf_config/orderer-tlsca/tlscacert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

orderers:
  orderer0:
    url: grpcs://hlf-orderer--ordorg1--orderer0:7050
    grpcOptions:
      ssl-target-name-override: orderer0.org1
    tlsCACerts:
      path: /hlf_config/orderer-tlsca/tlscacert.pem

peers:
  peer0.org1:
    url: grpcs://hlf-peer--org1--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hlf_config/orderer-tlsca/tlscacert.pem
  peer0.org2:
    url: grpcs://hlf-peer--org2--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /hlf_config/orderer-tlsca/tlscacert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/config_solo_raft/mychannel.tx
    created: true
    orderers:
      - orderer0
    peers:
      peer0.org1:
        eventSource: true
      peer0.org2:
        eventSource: true

    contracts:
      - id: fabcar
        version: "1.0"
        language: node
        path: /caliper-chaincode
        # metadataPath: src/fabric/samples/marbles/go/metadata
