name: Calier test
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.1.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /etc/hyperledger/fabric/msp/keystore/key.pem
      clientSignedCert:
        path: /etc/hyperledger/fabric/msp/signcerts/cert.pem

# organizations:
#   - mspid: org1MSP
#     identities:
#       certificates:
#         - name: "Admin"
#           admin: true
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/admin-msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/admin-msp/signcerts/cert.pem"
#         - name: "User1"
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/msp/signcerts/cert.pem"
#     connectionProfile:
#       path: "networks/profile-org1.yaml"

#       discover: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1
    certificateAuthorities:
      - ca-Org1
    adminPrivateKey:
      path: /etc/hyperledger/fabric/admin-msp/keystore/key.pem
      # pem: |
      #   -----BEGIN PRIVATE KEY-----
      #   MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgN270A2FEtfYadXjX
      #   g5sB4rOeoqVXzPmlNJTAzHtAtqKhRANCAAQr/1msTgLJAQyzbwE6Zi5SsmEntVbX
      #   yLVNzMdYsr11/Q5CjeULXBuU0ENYbOVZIWJCHOyXnvG3s3jUf33UH0Cw
      #   -----END PRIVATE KEY-----
    signedCert:
      path: /etc/hyperledger/fabric/msp/signcerts/cert.pem
      # pem: |
      #   -----BEGIN CERTIFICATE-----
      #   MIICAzCCAaqgAwIBAgIQBQwMnhYG/6G2bQJhWezqRjAKBggqhkjOPQQDAjBbMQsw
      #   CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
      #   YW5jaXNjbzENMAsGA1UEChMEb3JnMTEQMA4GA1UEAxMHY2Eub3JnMTAeFw0yMTA0
      #   MTMxMDA1MDBaFw0zMTA0MTExMDA1MDBaMF4xCzAJBgNVBAYTAlVTMRMwEQYDVQQI
      #   EwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMQ0wCwYDVQQLEwRw
      #   ZWVyMRMwEQYDVQQDEwpwZWVyMC5vcmcxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
      #   QgAEumyYxoy50J3JQ5BBd6nUHWId1dS3Ai2QQ/zuaVOcK9EGDmab3B/9zsYmRpoV
      #   nHmv5Bs7jrGABBFwxDUHoEpCkKNNMEswDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB
      #   /wQCMAAwKwYDVR0jBCQwIoAgiRLrKcc1yCAB9BmVXkOQDKnuRATJT+264SSO6K7C
      #   dKgwCgYIKoZIzj0EAwIDRwAwRAIgOTqEe5FN0vR9N6SbSQmTkAtUefrP9HwV1biA
      #   b+BgisECIGf7x+8tTi2MAaCSquQF5zE1/rXhdPyj7kG4/b0O0GfE
      #   -----END CERTIFICATE-----
certificateAuthorities:
  ca-Org1:
    url: http://10.233.19.210:7054
    httpOptions:
      verify: false
    caName: ca-Org1
    # tlsCACerts:
    #   path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

orderers:
  orderer0:
    url: grpc://hlf-orderer--ordorg1--orderer0:7050
    grpcOptions:
      ssl-target-name-override: orderer0.org1
    # tlsCACerts:
    #   path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem

peers:
  peer0.org1:
    url: grpc://hlf-peer--org1--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1
      grpc.keepalive_time_ms: 600000
    # tlsCACerts:
    #   path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/config_solo_raft/mychannel.tx
    created: true
    orderers:
      - orderer0
    peers:
      peer0.org1:
        eventSource: true

    contracts:
      - id: fabcar
        version: "1.0"
        language: node
        path: fabric/samples/marbles/go
        # metadataPath: src/fabric/samples/marbles/go/metadata
