name: Calier test
version: "1.0"
# mutual-tls: false

caliper:
  blockchain: fabric

# channels:
#   - channelName: mychannel
#     contracts:
#       - id: fabcar
info:
  Version: 2.1.0
  Size: 2 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /etc/hyperledger/fabric/msp/keystore/priv_sk
      clientSignedCert:
        path: /etc/hyperledger/fabric/msp/signcerts/cert.pem

# organizations:
#   - mspid: org1MSP
#     identities:
#       certificates:
#         - name: "Admin"
#           admin: true
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/admin-msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/admin-msp/signcerts/cert.pem"
#         - name: "User1"
#           clientPrivateKey:
#             path: "/etc/hyperledger/fabric/msp/keystore/priv_sk"
#           clientSignedCert:
#             path: "/etc/hyperledger/fabric/msp/signcerts/cert.pem"
#     connectionProfile:
#       path: "networks/profile-org1.yaml"
#       discover: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
    adminPrivateKey:
      path: /etc/hyperledger/fabric/admin-msp/keystore/priv_sk
    signedCert:
      path: /etc/hyperledger/fabric/msp/signcerts/cert.pem

orderers:
  orderer0.example.com:
    url: grpcs://hlf-orderer--ordorg1--orderer0:7050
    grpcOptions:
      ssl-target-name-override: orderer0.org1
    tlsCACerts:
      path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://peer0-org1:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem

certificateAuthorities:
  ca.org1.example.com:
    url: https://hlf-ca--org1:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /etc/hyperledger/fabric/msp/tlscacerts/tlsca.org1-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

channels:
  mychannel:
    # configBinary: networks/fabric/config_solo_raft/mychannel.tx
    created: true
    orderers:
      - orderer0.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true

    contracts:
      - id: fabcar
        version: "1.0"
        language: node
        path: fabric/samples/marbles/go
        # metadataPath: src/fabric/samples/marbles/go/metadata
