# Default values for hlf-kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
retryCount: 4

hyperledgerVersion: 2.2.0

tlsEnabled: false

# this should be set to true for TLS
useActualDomains: false

# adds additional DNS entries to /etc/hosts files
# this value should be provided if either tlsEnabled or useActualDomains is set to true
hostAliases: []

logLevel: grpc=debug:info

flow:
  channel:
    # should we run top level channel flows in parallel?
    parallel: false
    # fill in this array with channel names to limit the channel flow only to these ones
    include: []
  join:
    # run channel join flows in parallel?
    parallel: true
  update:
    # run channel update flows in parallel?
    parallel: true
