name: Calier test
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.2.1
  Distribution: Kubernetes
  Size: 2 Orgs with 2 Peer
  StateDB: CouchDB
  Orderer: "Orgs: 1, Orderers: 3"
  OrdererConsensus: "etcdraft"
  OrdererAddress: "orderer0.orgorderer1| orderer1.orgorderer1| orderer2.orgorderer1"
  LedgerBatchTimeout: "2s"
  LedgerBatchSize: "MaxMessageCount:100 | AbsoluteMaxBytes:2 MB | PreferredMaxBytes:2 MB"

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /etc/hyperledger/fabric/org1/msp/keystore/key.pem
      clientSignedCert:
        path: /etc/hyperledger/fabric/org1/msp/signcerts/cert.pem
      connection:
        timeout:
          peer:
            endorser: 300
  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: /etc/hyperledger/fabric/org2/msp/keystore/key.pem
      clientSignedCert:
        path: /etc/hyperledger/fabric/org2/msp/signcerts/cert.pem
      connection:
        timeout:
          peer:
            endorser: 300

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1
      - peer1.org1
    certificateAuthorities:
      - ca-Org1
    adminPrivateKey:
      path: /etc/hyperledger/fabric/org1/msp/keystore/key.pem
    signedCert:
      path: /etc/hyperledger/fabric/org1/msp/signcerts/cert.pem
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2
    certificateAuthorities:
      - ca-Org2
    adminPrivateKey:
      path: /etc/hyperledger/fabric/org2/msp/keystore/key.pem
    signedCert:
      path: /etc/hyperledger/fabric/org2/msp/signcerts/cert.pem

certificateAuthorities:
  ca-Org1:
    url: http://hlf-ca--org1.default.svc.cluster.local:7054
    httpOptions:
      verify: false
    caName: ca-Org1
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
  ca-Org2:
    url: http://hlf-ca--org2.default.svc.cluster.local:7054
    httpOptions:
      verify: false
    caName: ca-Org2
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

orderers:
  orderer0:
    url: grpc://hlf-orderer--ordorg1--orderer0:7050
    grpcOptions:
      ssl-target-name-override: orderer0.org1
      hostnameOverride: orderer0.org1
  orderer1:
    url: grpc://hlf-orderer--ordorg1--orderer1:7050
    grpcOptions:
      ssl-target-name-override: orderer1.org1
      hostnameOverride: orderer1.org1
  orderer2:
    url: grpc://hlf-orderer--ordorg2--orderer0:7050
    grpcOptions:
      ssl-target-name-override: orderer0.org2
      hostnameOverride: orderer0.org2

peers:
  peer0.org1:
    url: grpc://hlf-peer--org1--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1
      hostnameOverride: peer0.org1
      grpc.keepalive_time_ms: 600000
  peer1.org1:
    url: grpc://hlf-peer--org1--peer1:7051
    grpcOptions:
      ssl-target-name-override: peer1.org1
      hostnameOverride: peer1.org1
      grpc.keepalive_time_ms: 600000
  peer0.org2:
    url: grpc://hlf-peer--org2--peer0:7051
    grpcOptions:
      ssl-target-name-override: peer0.org2
      hostnameOverride: peer0.org2
      grpc.keepalive_time_ms: 600000

channels:
  mychannel:
    created: true
    orderers:
      - orderer0
      - orderer1
      - orderer2

    peers:
      peer0.org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    contracts:
      - id: asset-transfer-basic
        version: "1.0"
        language: node
        path: /caliper-chaincode
