apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: caliper-manager
  name: caliper-manager
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: caliper-manager
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Never
      containers:
        - name: caliper
          image: hyperledger/caliper:0.4.2
          command: 
          - /bin/sh
          - "-c"
          - |
            /bin/sh <<'EOF'

            caliper launch manager
            echo "Start pushing the generated report.html to the git repository..."
            ls /hyperledger/caliper/workspace/
            # Modify the git clone URL if needed follwing the structure https://cli:<project_access_token>@<repo_url>
            # Example of Repo URL: gitlab.lrz.de/ga32nac/hyperledgerlab2-reports.git
            if [ -f /caliper-report-git/.env ]
            then
              export $(cat .env | sed 's/#.*//g' | xargs)
              git clone https://cli:$PROJECT_ACCESS_TOKEN@$REPOSITORY_URL
              git config --global user.email "$GIT_USER_EMAIL" 
              git config --global user.name "$GIT_USER_NAME" 
              NOW_TIMESTAMP="$(date +'%s')"
              NOW="$(date)"
              DIR_NAME="report_$NOW_TIMESTAMP"
              mkdir hyperledgerlab2-reports/$DIR_NAME
              cp report.html hyperledgerlab2-reports/$DIR_NAME/
              cd hyperledgerlab2-reports/
              git add $DIR_NAME
              git commit -m "Report $NOW"
              git push -u origin master
              echo "The generated report.html has been successfully pushed to the git repo..."
            else 
              echo "No git repository is defined to upload the report.html file."
            fi

            exit 123
            EOF
          tty: true
          workingDir: /hyperledger/caliper/workspace
          env:
            - name: CALIPER_BIND_SUT
              value: fabric:2.1
            - name: CALIPER_BENCHCONFIG
              value: /caliper-benchmark/config.yaml
            - name: CALIPER_NETWORKCONFIG
              value: /caliper-network/networkConfig.yaml
            - name: CALIPER_FABRIC_GATEWAY_ENABLED
              value: "true"
            - name: CALIPER_FABRIC_GATEWAY_LOCALHOST
              value: "false"
            - name : CALIPER_FABRIC_GATEWAY_USEGATEWAY 
              value: "true"
            - name: CALIPER_FABRIC_GATEWAY_DISCOVERY
              value: "false"
            - name: CALIPER_FLOW_ONLY_TEST
              value: "true"
            - name: CALIPER_WORKSPACE
              value: /hyperledger/caliper/workspace
            - name: CALIPER_BIND_ARGS
              value: "-g"
            - name: CALIPER_PROJECTCONFIG 
              value: /caliper-config/caliper.yaml
            - name: CXXFLAGS
              value: "-Wno-cast-function-type"
            - name: CALIPER_WORKER_REMOTE
              value: "true"
            - name: CALIPER_WORKER_COMMUNICATION_METHOD
              value: "mqtt"
            - name: CALIPER_WORKER_COMMUNICATION_ADDRESS
              value: "mqtt://mosquitto.default.svc.cluster.local:1883"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric/org1/peer-msp/
              name: peer-msp1
            - mountPath: /etc/hyperledger/fabric/org2/peer-msp/
              name: peer-msp2

            - mountPath: /etc/hyperledger/fabric/org1/msp/
              name: peer-admin-msp1
            - mountPath: /etc/hyperledger/fabric/org2/msp/
              name: peer-admin-msp2

            - mountPath: /etc/hyperledger/fabric/ordorg1-tlsca
              name: ordorg1-tlsca
            - mountPath: /etc/hyperledger/fabric/ordorg2-tlsca
              name: ordorg2-tlsca

            - mountPath: /caliper-benchmark
              name: caliper-benchmark
            - mountPath: /caliper-network
              name: caliper-network
            - mountPath: /caliper-workload
              name: caliper-workload
            - mountPath: /caliper-chaincode
              name: caliper-chaincode
            - mountPath: /hyperledger/caliper/workspace/
              name: caliper-workspace
            - mountPath: /caliper-config
              name: caliper-config
            - mountPath: /caliper-report-git
              name: caliper-report-git
      volumes:
        - name: caliper-workspace
          emptyDir: {}
        - name: caliper-report-git
          configMap:
            name: caliper-report-git
        - name: caliper-benchmark
          configMap:
            name: benchmarks
        - name: caliper-network
          configMap:
            name: network
        - name: caliper-workload
          configMap:
            name: workload
        - name: caliper-config
          configMap:
            name: caliper-config
        - name: caliper-chaincode
          configMap:
            name: hlf-chaincode--asset-transfer-basic

        - name: peer-msp1
          secret:
            secretName: hlf-peer--org1--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-msp2
          secret:
            secretName: hlf-peer--org2--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp1
          secret:
            secretName: hlf-peer--org1--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp2
          secret:
            secretName: hlf-peer--org2--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: ordorg1-tlsca
          secret:
            secretName: hlf-orderer--ordorg1-tlsca
        - name: ordorg2-tlsca
          secret:
            secretName: hlf-orderer--ordorg2-tlsca
