apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: caliper-worker
  name: caliper-worker
spec:
  parallelism: 10
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: caliper-worker
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Never
      containers:
        - name: caliper-worker
          image: hyperledger/caliper:0.4.2
          command:
            - caliper
          args:
            - launch
            - worker
          tty: true
          env:
            - name: CALIPER_BIND_SUT
              value: fabric:2.1
            - name: CALIPER_BENCHCONFIG
              value: /caliper-benchmark/config.yaml
            - name: CALIPER_NETWORKCONFIG
              value: /caliper-network/networkConfig.yaml
            - name: CALIPER_FABRIC_GATEWAY_ENABLED
              value: "true"
            - name: CALIPER_FABRIC_GATEWAY_LOCALHOST
              value: "false"
            - name: CALIPER_FLOW_ONLY_TEST
              value: "true"
            - name: CALIPER_BIND_ARGS
              value: "-g"
            - name: CALIPER_REPORT_PATH 
              value: /hyperledger/caliper/workspace/report/
            - name: CXXFLAGS
              value: "-Wno-cast-function-type"
            - name: CALIPER_WORKER_REMOTE
              value: "true"
            - name: CALIPER_WORKER_COMMUNICATION_METHOD
              value: "mqtt"
            - name: CALIPER_WORKER_COMMUNICATION_ADDRESS
              value: "mqtt://mosquitto.default.svc.cluster.local:1883"

          volumeMounts:
            - mountPath: /etc/hyperledger/fabric/org1/peer-msp/
              name: peer-msp1
            - mountPath: /etc/hyperledger/fabric/org2/peer-msp/
              name: peer-msp2

            - mountPath: /etc/hyperledger/fabric/org1/msp/
              name: peer-admin-msp1
            - mountPath: /etc/hyperledger/fabric/org2/msp/
              name: peer-admin-msp2

            - mountPath: /etc/hyperledger/fabric/ordorg1-tlsca
              name: ordorg1-tlsca
            - mountPath: /etc/hyperledger/fabric/ordorg2-tlsca
              name: ordorg2-tlsca

            - mountPath: /caliper-benchmark
              name: caliper-benchmark
            - mountPath: /caliper-network
              name: caliper-network
            - mountPath: /caliper-workload
              name: caliper-workload
            - mountPath: /caliper-chaincode
              name: caliper-chaincode
            - mountPath: /hyperledger/caliper/workspace/report/
              name: caliper-workspace
            - mountPath: /hyperledger/caliper/workspace/
              name: caliper-config
      volumes:
        - name: caliper-workspace
          hostPath:
            path: /home/caliper-workspace
            type: DirectoryOrCreate
        - name: caliper-benchmark
          configMap:
            name: benchmarks
        - name: caliper-network
          configMap:
            name: network
        - name: caliper-workload
          configMap:
            name: workload
        - name: caliper-config
          configMap:
            name: caliper-config
        - name: caliper-chaincode
          configMap:
            name: hlf-chaincode--asset-transfer-basic

        - name: peer-msp1
          secret:
            secretName: hlf-peer--org1--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-msp2
          secret:
            secretName: hlf-peer--org2--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp1
          secret:
            secretName: hlf-peer--org1--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: peer-admin-msp2
          secret:
            secretName: hlf-peer--org2--admin-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.org1-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem

        - name: ordorg1-tlsca
          secret:
            secretName: hlf-orderer--ordorg1-tlsca
        - name: ordorg2-tlsca
          secret:
            secretName: hlf-orderer--ordorg2-tlsca
