apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caliper
  name: caliper
spec:
  selector:
    matchLabels:
      app: caliper
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: caliper
    spec:
      containers:
        - env:
            - name: CALIPER_BIND_SUT
              value: fabric:2.2
            - name: CALIPER_BENCHCONFIG
              value: benchmarks/myAssetBenchmark.yaml
            - name: CALIPER_NETWORKCONFIG
              value: networks/networkConfig.yaml
            - name: CALIPER_FABRIC_GATEWAY_ENABLED
              value: "true"
            - name: CALIPER_FLOW_ONLY_TEST
              value: "true"
          image: hyperledger/caliper:0.4.2
          name: caliper
          command: ["/bin/bash", "-c", "--"]
          args:
            ["while true; do sleep 30; done;"]
            # command:
          #   - caliper
          # args:
          #   - --version
          #   # - manager
          tty: true
          volumeMounts:
            - mountPath: /hyperledger/caliper/workspace
              name: caliper-workspace
            - mountPath: /hyperledger/caliper/fabric-samples
              name: fabric-workspace
            - mountPath: /etc/hyperledger/fabric/msp/
              name: peer-msp
          workingDir: /hyperledger/caliper/workspace
      restartPolicy: Always
      volumes:
        - name: caliper-workspace
          hostPath:
            path: /home/ubuntu/hyperledgerlab2/hyperledgerFabric/benchmarking
            type: DirectoryOrCreate
        - name: fabric-workspace
          hostPath:
            path: /home/ubuntu/hyperledgerlab2/hyperledgerFabric
            type: DirectoryOrCreate
        - name: peer-msp
          secret:
            secretName: hlf-peer--org1--peer0-msp
            items:
              - key: config.yaml
                path: config.yaml
              - key: cert.pem
                path: signcerts/cert.pem
              - key: key.pem
                path: keystore/key.pem
              - key: cacert.pem
                path: cacerts/ca.{{ $org.Domain}}-cert.pem
              - key: tlscacert.pem
                path: tlscacerts/cert.pem
